apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-hello
    app.kubernetes.io/instance: argocd-hello
  name: argocd-hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argocd-hello
